# AWS CodeBuild pipeline
version: 0.2
env:
  variables:
    S3_BUCKET: "doccheck-cv.pfeierabend.de"
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production --aot
  post_build:
     commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
